#!/usr/bin/env python3
"""Generate FILE_INVENTORY.md from the git-tracked file list.

The inventory used to be hand-maintained and drifted from the real tree (e.g.
it listed wiki/KNX.md while the file was wiki/Knx.md). Regenerating it from
`git ls-files` makes drift impossible. The committed FILE_INVENTORY.md is the
source presented to readers; this script is how it stays accurate.

Run after adding, renaming or removing tracked files:

    python3 tools/generate_file_inventory.py

tools/check_repo.py asserts the committed file matches the generator output,
so a stale inventory fails CI.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INVENTORY = ROOT / "FILE_INVENTORY.md"


def tracked_files() -> list[str]:
    result = subprocess.run(
        ["git", "ls-files"],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    return sorted(line for line in result.stdout.splitlines() if line)


def render(files: list[str]) -> str:
    lines = [
        "# File inventory",
        "",
        "Auto-generated by `tools/generate_file_inventory.py` from "
        "`git ls-files`. Do not edit by hand; run the generator instead.",
        "",
    ]
    for path in files:
        lines.append(f"- `{path}`")
    lines.append("")
    return "\n".join(lines)


def generate() -> None:
    files = tracked_files()
    INVENTORY.write_text(render(files), encoding="utf-8")
    print(f"Wrote {len(files)} tracked paths to {INVENTORY.relative_to(ROOT)}")


def check() -> int:
    """Exit 0 if the committed inventory matches the generator output."""
    expected = render(tracked_files())
    actual = INVENTORY.read_text(encoding="utf-8") if INVENTORY.exists() else ""
    if actual == expected:
        return 0
    sys.stderr.write(
        "FILE_INVENTORY.md is out of sync with git ls-files. Regenerate "
        "with: python3 tools/generate_file_inventory.py\n"
    )
    return 1


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Only verify the committed inventory matches; do not write.",
    )
    args = parser.parse_args()
    if args.check:
        raise SystemExit(check())
    generate()
