[platformio]
default_envs = idm-native
src_dir = main
include_dir = main

[env:idm-native]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
board = esp32-c3-devkitm-1
framework = espidf
board_build.partitions = partitions.csv
board_upload.flash_size = 4MB
build_flags =
    -std=gnu++20
    -Wall
    -Wextra
build_unflags =
    -std=c++11
    -std=gnu++11
monitor_speed = 115200
