i2c:
  sda: GPIO8
  scl: GPIO9
sensor:
  - platform: sht4x
    temperature:
      name: Local Temperature
      id: idm_room_temperature
    humidity:
      name: Local Humidity
      id: idm_room_humidity
