name: YAML check

on:
  push:
    paths:
      - "**/*.yaml"
      - "**/*.yml"
  pull_request:
    paths:
      - "**/*.yaml"
      - "**/*.yml"

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .
          strict: false
